# vim: nospell
language: generic
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.stack
    - .stack-work/install

matrix:
  include:
    - env: CUDA=6.5-14 GHC=8.2.1 CABAL=2.0
      compiler: "GHC 8.2"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-2.0, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.0-28 GHC=8.2.1 CABAL=2.0
      compiler: "GHC 8.2"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-2.0, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.5-18 GHC=8.2.1 CABAL=2.0
      compiler: "GHC 8.2"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-2.0, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=8.0.61-1 GHC=8.2.1 CABAL=2.0
      compiler: "GHC 8.2"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-2.0, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=6.5-14 GHC=8.0.1 CABAL=1.24
      compiler: "GHC 8.0"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.24, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.0-28 GHC=8.0.1 CABAL=1.24
      compiler: "GHC 8.0"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.24, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.5-18 GHC=8.0.1 CABAL=1.24
      compiler: "GHC 8.0"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.24, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=8.0.61-1 GHC=8.0.1 CABAL=1.24
      compiler: "GHC 8.0"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.24, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=6.5-14 GHC=7.10.3 CABAL=1.22
      compiler: "GHC 7.10"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.22, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.0-28 GHC=7.10.3 CABAL=1.22
      compiler: "GHC 7.10"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.22, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.5-18 GHC=7.10.3 CABAL=1.22
      compiler: "GHC 7.10"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.22, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=8.0.61-1 GHC=7.10.3 CABAL=1.22
      compiler: "GHC 7.10"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.22, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=6.5-14 GHC=7.8.4 CABAL=1.18
      compiler: "GHC 7.8"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.18, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.0-28 GHC=7.8.4 CABAL=1.18
      compiler: "GHC 7.8"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.18, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=7.5-18 GHC=7.8.4 CABAL=1.18
      compiler: "GHC 7.8"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.18, happy-1.19.5, alex-3.1.7 ] }}

    - env: CUDA=8.0.61-1 GHC=7.8.4 CABAL=1.18
      compiler: "GHC 7.8"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ cabal-install-1.18, happy-1.19.5, alex-3.1.7 ] }}

    # - env: CUDA=8.0.61-1 GHC=head CABAL=head
    #   compiler: "GHC HEAD"
    #   addons: { apt: { sources: [ hvr-ghc ], packages: [ ghc-head, cabal-install-head, happy-1.19.5, alex-3.1.7 ] }}

  # allow_failures:
  #   - env: CUDA=8.0.61-1 GHC=head CABAL=head


before_install:
  - export PATH=/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$HOME/.cabal/bin:$PATH
  - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh
  - source .travis/update-ghc-settings.sh
  - travis_retry stack install c2hs

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - c2hs --version
  - nvcc --version
  - |
      if [ ${GHC} == head -o ! -e stack.yaml ]; then
        travis_retry cabal install --only-dependencies
      else
        travis_retry stack build --only-dependencies --no-terminal --no-haddock-deps
      fi

script:
  - |
      if [ ${GHC} == head -o ! -e stack.yaml ]; then
        travis_retry cabal install
        travis_retry cabal haddock
      else
        travis_retry stack build --no-terminal --haddock --no-haddock-deps
      fi

after_success:
  - source .travis/update-accelerate-buildbot.sh

after_failure:
  - dmesg
  - ls -R /usr/local/cuda*

