# vim: nospell
#
language: c
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.stack/snapshots
    - $HOME/.local/bin
    - .stack-work/install

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - alex-3.1.7
      - happy-1.19.5

compiler:
  - GHC-8.6.3
  - GHC-8.4.4
  - GHC-8.2.2
  - GHC-8.0.2
  - GHC-7.10.3
  - GHC-7.8.4

env:
  # global:
  matrix:
    - CUDA=10.1.105-1
    - CUDA=10.0.130-1
    - CUDA=8.0.61-1
    - CUDA=7.5-18
    - CUDA=7.0-28

matrix:
  fast_finish: true
  # allow_failures:

before_install:
  - export GHC=${CC:4}
  - unset CC
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh
  - source .travis/update-ghc-settings.sh

  # # ghc-8.6 builds a broken version of c2hs
  # - |
  #     if [ ${GHC%.*} == "8.6" -a ! -x "$(which c2hs)" ]; then
  #       travis_retry stack --stack-yaml=stack-8.4.yaml setup --no-terminal --no-system-ghc
  #       travis_retry stack --stack-yaml=stack-8.4.yaml install c2hs --fast --no-terminal
  #     fi

  # build environment
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - nvcc --version

install:
  - travis_retry stack build --fast --only-dependencies --no-terminal

script:
  - travis_retry stack build --fast --no-terminal --haddock --no-haddock-deps

after_success:
  - source .travis/update-accelerate-buildbot.sh

after_failure:
  - dmesg
  - ls -R /usr/local/cuda*

